### ISSUE TITLE
Encode sharing links to avoid parens etc

### ISSUE THREAD

**Issue by jmandel** [brianpos/fhirpath-lab#24]
`https://fhirpath-lab.azurewebsites.net/FhirPath?expression=group.select(%0A%20%20element.code.aggregate(%0A%20%20%20%20%24total.union(%0A%20%20%20%20%20%20%24total.first()%20%26%20'%2C%20'%20%26%20%24this)%2C%0A%20%20%20%20%24this.source)%0A%20%20.skip(1))%0A.trace(%22source-element-tuple%22)%0A.isDistinct()%0A%20%20%0A%0A&resource=https%3A%2F%2Fhapi.fhir.org%2FbaseR4%2FConceptMap%2F6850420&terminologyserver=https%3A%2F%2Fsqlonfhir-r4.azurewebsites.net%2Ffhir`

^ This link fails in zulip, as in [click here](https://fhirpath-lab.azurewebsites.net/FhirPath?expression=group.select(%0A%20%20element.code.aggregate(%0A%20%20%20%20%24total.union(%0A%20%20%20%20%20%20%24total.first()%20%26%20'%2C%20'%20%26%20%24this)%2C%0A%20%20%20%20%24this.source)%0A%20%20.skip(1))%0A.trace(%22source-element-tuple%22)%0A.isDistinct()%0A%20%20%0A%0A&resource=https%3A%2F%2Fhapi.fhir.org%2FbaseR4%2FConceptMap%2F6850420&terminologyserver=https%3A%2F%2Fsqlonfhir-r4.azurewebsites.net%2Ffhir). May be an underlying zulip bug, but still probably worth creating links that do something like b64urlencoding the whole set of args to avoid surprises.

**Comment by jmandel** [comment]
I'll also submit a Zulip issue.

**Comment by jmandel** [comment]
The issue is the `'` characters for some reason.

**Comment by jmandel** [comment]
https://github.com/zulip/zulip/issues/22569

**Comment by brianpos** [comment]
I'll do a base64 encoded version of the params too.
(I do URLencode all the parts so it **should** be fine)
