### ISSUE TITLE
Allow `Ctrl+Enter` to re-run the query

### ISSUE THREAD

**Issue by vadi2** [brianpos/fhirpath-lab#30]
When iterating on building a query, it can be quite handy to be able to re-run it with `Ctrl+Enter` without requiring the use of a mouse.

**Comment by brianpos** [comment]
Alt+G already supports this, and is in the tooltip on the button.

**Comment by vadi2** [comment]
Aha. It's not really idiomatic to use alt+g, ctrl+enter is far more popular. Could it be an option?
