### ISSUE TITLE
Allow searching within expression

### ISSUE THREAD

**Issue by vadi2** [brianpos/fhirpath-lab#31]
It would be great if we could search within expressions to find examples of certain function use - for example, get me all expressions that make use of `aggregate()`.

**Comment by brianpos** [comment]
Do you mean into the library, or inside the expression in the UI already?

**Comment by vadi2** [comment]
That would be within the library

**Comment by brianpos** [comment]
So an advanced search of sorts that checks inside all the expressions?

**Comment by vadi2** [comment]
That's right!

**Comment by vadi2** [comment]
As an example I wanted to give a junior an example of how to use fhirpath for search for a value within an extension, but I couldn't do that using the fhirpath lab ui - had to turn to a search engine instead. Would be great if cases like this could be covered by the lab :)

**Comment by brianpos** [comment]
This is now implemented on the fhir.forms-lab.com server (which should be the default from the lab)

**Comment by vadi2** [comment]
Nice. Should I see anything new in the UI of https://fhirpath-lab.com/Library ?

**Comment by vadi2** [comment]
This is the default for me, even in private mode:

![image](https://github.com/brianpos/fhirpath-lab/assets/110988/72a8f222-904a-4a0a-acac-d3e80168d113)

Changing the two FHIR server endpoints worked (although one of them is asking for OAuth credentials):

![image](https://github.com/brianpos/fhirpath-lab/assets/110988/59917c5e-bf80-4cd4-90aa-1d64096b5c4e)

![image](https://github.com/brianpos/fhirpath-lab/assets/110988/9e3b34d2-aef9-40da-a206-63a66ccdb7f3)

Thanks!
