### ISSUE TITLE
Don't set context by default

### ISSUE THREAD

**Issue by vadi2** [brianpos/fhirpath-lab#33]
Setting the context is a great optional feature, but the fact that it's set by default can really trip you up. 

I've developed a habit to clear it out every time the tool loads to do my work - that's probably not the best UX?

**Comment by brianpos** [comment]
Getting a reset expression button to sweep away the current values.
Do you think it's worth adding that same button to the test resource too?

**Comment by vadi2** [comment]
I don't think so, because you always clear and replace the test resource with something else. That's different from the context where you might just want to traverse from the root and not set it.
